#!/usr/bin/env node
/**
 * Zero-dependency build.
 *
 * ── WHY THIS EXISTS AT ALL ─────────────────────────────────────────────────
 * CLAUDE.md said "there is no build step and `src/` ships as-is", and for a
 * long time that was right. Two things changed:
 *
 * 1. The compliance guards must run against the ARTEFACT, not the source. A
 *    term that survives into the deployed bundle is the one that matters; a
 *    term in a file that never ships is not a finding.
 * 2. `flags.js` documented an honest limitation — flipping the flag removed
 *    Module B's BEHAVIOUR but not its BYTES, so an entertainment-only build
 *    still shipped health-adjacent copy and could not truthfully answer
 *    Google Play's Health declaration. This build closes that gap.
 *
 * It stays true to the spirit of the original decision: no bundler, no npm
 * dependencies, no transform. `dist/` is a copy of `src/`, and for the
 * entertainment flavour two Module B files are REPLACED BY STUBS so their copy
 * is genuinely absent from the artefact.
 *
 * Stubs rather than deletion because `rules.js` and `analysis.js` import these
 * modules statically. Deleting the files would break the import graph; stubbing
 * them keeps it valid while removing every health-adjacent string.
 *
 * NOTE ON FILE WRITES: this is a Node script on purpose. A PowerShell
 * Get-Content/Set-Content round-trip double-encodes every non-ASCII character
 * and has already corrupted two files in this repo (CLAUDE.md item 18b).
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, statSync, copyFileSync }
  from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(REPO, "src");
const DIST = join(REPO, "dist");

/** Read the flag without importing (the build must not execute app code). */
function readFlavour() {
  const text = readFileSync(join(SRC, "flags.js"), "utf8");
  const m = text.match(/MODULE_B_SAFETY_REFERRALS\s*=\s*(true|false)/);
  if (!m) throw new Error("build: could not read MODULE_B_SAFETY_REFERRALS from src/flags.js");
  return m[1] === "true"
    ? { moduleB: true, name: "wellness" }
    : { moduleB: false, name: "entertainment-only" };
}

const walk = (dir) => readdirSync(dir).flatMap((n) => {
  const p = join(dir, n);
  return statSync(p).isDirectory() ? walk(p) : [p];
});

/* Module B replacements for the entertainment flavour. Same export surface,
 * no health-adjacent copy, no thresholds, nothing to render. */
const STUB_SAFETY = `/* Entertainment build: Module B is not shipped.
 * Generated by scripts/build.js. Same export surface as the real adapter so
 * the import graph stays valid, with no referral logic and no clinical copy. */
export const SAFETY_THRESHOLDS = Object.freeze({});
export const isSafetyEnabled = () => false;
export function evaluateSafety() {
  return { enabled: false, assessable: false, referrals: [], reason: null };
}
export const SAFETY_IS_NEVER_BILLED = true;
`;

const STUB_RULES_B = `/* Entertainment build: Module B is not shipped.
 * Generated by scripts/build.js. No safety gates, no advisory, no disclaimer
 * text -- none of it is in this artefact. */
export const MODULE_B_DISCLAIMER = "";
export const RULES_B = [];
`;

/* The RENDERER is Module B too. Stubbing only the content left the referral
 * headings ("see a clinician", "dermatologist") in the entertainment artefact,
 * where they would have to be explained on a store declaration despite being
 * unreachable. Views ship with their content or not at all. */
const STUB_MODULE_B_VIEW = `/* Entertainment build: Module B is not shipped.
 * Generated by scripts/build.js. Same export surface, renders nothing. */
export const renderReferrals = () => "";
export const renderHaltNotice = () => "";
export const renderAdvisories = () => "";
export function renderMeasurementLimits(baseline, notMeasured) {
  const list = (notMeasured || []).join(", ").replace(/_/g, " ");
  return \`
    <div class="limits">
      <p class="eyebrow">What this photo could and couldn't measure</p>
      <p class="notmeasured">Not checked: \${list}</p>
      <p class="muted" style="font-size:.78rem">Those need a model trained on
        labelled photographs, which this build doesn't have. Nothing above is a
        check for them.</p>
    </div>\`;
}
`;

function build() {
  const flavour = readFlavour();

  rmSync(DIST, { recursive: true, force: true });
  mkdirSync(DIST, { recursive: true });

  let copied = 0;
  for (const file of walk(SRC)) {
    const rel = relative(SRC, file);
    const dest = join(DIST, rel);
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(file, dest);
    copied++;
  }

  const stubbed = [];
  if (!flavour.moduleB) {
    writeFileSync(join(DIST, "adapters", "safety.js"), STUB_SAFETY, "utf8");
    writeFileSync(join(DIST, "rules-b.js"), STUB_RULES_B, "utf8");
    writeFileSync(join(DIST, "modulebview.js"), STUB_MODULE_B_VIEW, "utf8");
    stubbed.push("adapters/safety.js", "rules-b.js", "modulebview.js");
  }

  // Recorded in the artefact so a store submission can be checked against what
  // was actually shipped rather than against what the flag said at the time.
  writeFileSync(join(DIST, "build-info.json"), JSON.stringify({
    flavour: flavour.name,
    moduleBShipped: flavour.moduleB,
    stubbedModules: stubbed,
  }, null, 2) + "\n", "utf8");

  console.log(`Built dist/ — flavour: ${flavour.name}`);
  console.log(`  ${copied} files copied`);
  console.log(stubbed.length
    ? `  ${stubbed.length} Module B module(s) stubbed out: ${stubbed.join(", ")}`
    : "  Module B shipped (wellness flavour)");

  if (copied === 0) {
    console.error("FAIL: build produced 0 files.");
    process.exit(1);
  }
}

build();
